package handlers

import (
	"encoding/json"
	"net/http"

	"github.com/aswinbennyofficial/sre-exercises/internals/database"
	"github.com/aswinbennyofficial/sre-exercises/internals/models"
	"github.com/rs/zerolog/log"
)

// CreateNewStudent is a handler function that creates a new student
// It reads the student details from the request body and inserts it into the database
// Id is auto-generated by the database
func CreateNewStudent(w http.ResponseWriter, r *http.Request) {
	var student models.Student
	err:=json.NewDecoder(r.Body).Decode(&student)
	if err!=nil{
		log.Error().Err(err).Caller().Msg("Error decoding the request body")
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	log.Debug().Msgf("Student Id: %d",student.ID)
	log.Debug().Msg("Student name: "+student.Name)
	log.Debug().Msg("Student phone: "+student.Phone)
	log.Debug().Msg("Student address: "+student.Address)


	// Insert the student into the database
	sqlStatement := `INSERT INTO Student (name, phone, address) VALUES ($1, $2, $3)`
	_,err=database.PgxPool.Exec(r.Context(), sqlStatement, student.Name, student.Phone, student.Address)
	if err!=nil{
		log.Error().Err(err).Caller().Msg("Error inserting student into the database")
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(`{"message":"New student created"}`))
}